# Generated by Django 4.2 on 2023-05-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_attemptquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequiz',
            name='right_ans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
