# Generated by Django 4.2 on 2023-05-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_attemptquiz_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequiz',
            name='right_ans',
        ),
    ]
