# Generated by Django 4.2 on 2023-05-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_coursequiz_right_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('upload', models.FileField(null=True, upload_to='study_material/')),
                ('remarks', models.TextField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_study_materials', to='main.course')),
            ],
            options={
                'verbose_name_plural': 'Course Study Materials',
            },
        ),
    ]
