# Generated by Django 4.2 on 2023-05-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_view',
            field=models.BigIntegerField(default=0),
        ),
    ]
