# Generated by Django 4.2 on 2023-05-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_student_login_via_otp_teacher_login_via_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='verify_status',
            new_name='varify_status',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='verify_status',
            new_name='varify_status',
        ),
    ]
