# Generated by Django 4.2 on 2023-05-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_teacher_facebook_url_teacher_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='twitter_url',
        ),
    ]
